apiVersion: apps/v1
kind: Deployment
metadata:
  name: highrisebot
  labels:
    app: highrisebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highrisebot
  template:
    metadata:
      labels:
        app: highrisebot
    spec:
      containers:
      - name: highrisebot-container
        image: protonalialol/highrise_bot:0.0.6
        imagePullPolicy: Always
        env:
        - name: test
          value: value
        - name: botMode
          value: Bot