apiVersion: apps/v1
kind: Deployment
metadata:
  name: highrisebot
  labels:
    app: highrisebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highrisebot
  template:
    metadata:
      labels:
        app: highrisebot
    spec:
      containers:
      - name: highrisebot-container
        image: protonalialol/highrise_bot:v0.1-test
        imagePullPolicy: Always
        env:
        - name: BOT_TYPE
          value: InstanceBot
        - name: ROOM_ID
          value: 63c08fb2d0187c1745407652
        - name: API_KEY
          value: 605989e0149119cb9095f303d86e43ea35eed73237fe52960c562800d8b277c5
        
